// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApi.Data;

namespace ToDoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210216230336_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("ToDoApi.Data.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35bbef83-2b66-4d94-b1b6-075b5172868f"),
                            Content = "Finish up work on latest feature",
                            CreatedDate = 1305581813669744640L,
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = new Guid("38560f1d-83aa-4824-a39d-f81b2ac4ae81"),
                            Content = "Make a bitmoji",
                            CreatedDate = 1305581813628784640L,
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = new Guid("e404faa1-7a06-41d2-87b8-7ddfb9e7300c"),
                            Content = "Buy bread",
                            CreatedDate = 1305581813587824640L,
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = new Guid("cf185182-88c1-4413-969d-733cea151b1a"),
                            Content = "Follow up with Sam RE Friday night",
                            CreatedDate = 1305581813546864640L,
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = new Guid("eb60226c-f9a0-44fc-887c-ec98ce39f433"),
                            Content = "Cat flea treatment",
                            CreatedDate = 1305581813459476480L,
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = new Guid("cc552a5d-a3e4-4e5e-bcb0-3ec3d249a3f9"),
                            Content = "Daily walk",
                            CreatedDate = 1305581813393141760L,
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = new Guid("ad35676c-81a0-48c3-8af6-4d8dd41671f0"),
                            Content = "Take out the rubbish",
                            CreatedDate = 1305581813239767040L,
                            Status = "DONE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
